### ISSUE TITLE
Issue with rmm mode (softfloat) in fcvt.s.w and fcvt.s.wu instructions

### ISSUE THREAD

**Issue by UrvishkumarPatel** [chipsalliance/SweRV-ISS#10]
I compiled whisper with "make SOFT_FLOAT=1".
I ran the following commands
```
whisper -i --isa imafdc
whisper> poke c mstatus 0x80007800
whisper> poke r x22 0xfee0001b
whisper> poke m 0 0xd00b4c53
whisper> step
#1 0 00000000 d00b4c53 f 18 ffffffffcb8ffff2  fcvt.s.w f24, x22, rmm  +
#1 0 00000000 d00b4c53 c 0003       00000001  fcvt.s.w f24, x22, rmm
whisper> peek f f24
0xffffffffcb8ffff2
```

The expected result is 0xffffffffcb8ffff3

**Comment by jrahmeh** [comment]
Hi Urvish,

I am getting the expected results. Please make sure you have the latest
from GitHub.

Joe

**Comment by jrahmeh** [comment]
I updated the makefile. Please try again with latest code from GitHub.

**Comment by UrvishkumarPatel** [comment]
Hi Joe,
It is working now with the updated Makefile

Thanks,
Urvish
