### ISSUE TITLE
Vector Extension version

### ISSUE THREAD

**Issue by Zissi-Lei** [chipsalliance/SweRV-ISS#12]
Hi,
I want to know what version of RISC-V Vector Extension that you implement in SweRV-ISS, thanks.

**Comment by jrahmeh** [comment]
Version 1.0

**Comment by Zissi-Lei** [comment]
OK, thanks! Now I can try to run vector instructions using SweRV-ISS!

**Comment by HamzaShabbir517** [comment]
hello @Zissi-Lei where you able to run vector instruction on Whisper ISS ?
