### ISSUE TITLE
Floating Point Register

### ISSUE THREAD

**Issue by HamzaShabbir517** [chipsalliance/SweRV-ISS#19]
Hello i have enable the single precision floating point to perform some test but it seem that the register file is according to double precision that is 64 bits. Is their any parameter to make the floating point register file length to 32 when we are using single precision only

And i also want to know about the vector extension as i try to run vector instruction but it gave me an illegal instruction error. and there is also no parameter to read vector register file

**Comment by jrahmeh** [comment]
Hi Hamza,

The code uses 64-bit wide registers and nan-boxing for storing single precision values into 64-bit-wide registers.  If the F extension is enabled and D extension is disabled, then the tracing/logging code will print the least significant 32-bits of the internal registers.  Please give this a try:  enable F and disable D.  You do this by using "--isa imaf".

Joe

**Comment by HamzaShabbir517** [comment]
is the vector extension is supported into whisper
