### ISSUE TITLE
Illegal Instruction Error

### ISSUE THREAD

**Issue by HamzaShabbir517** [chipsalliance/SweRV-ISS#23]
Previously I install the same Whisper ISS on my ubuntu machine but when i am performing the same procedure for my another machine but i am getting this error i have tried to build it several times but getting the same error. I am attaching the snap of the error 

![Screenshot from 2022-07-08 21-02-58](https://user-images.githubusercontent.com/53592110/178029286-3208161a-ff55-4f10-a887-5468442b4137.png)

**Comment by HamzaShabbir517** [comment]
Need help with this issue

**Comment by HamzaShabbir517** [comment]
@jrahmeh i have run the commands as you mention and i got the following output 

![Screenshot from 2022-09-07 10-34-46](https://user-images.githubusercontent.com/53592110/188796809-092b6823-3539-4afd-b141-c57da67d4c28.png)

**Comment by avishaitvila** [comment]
Did you compile with -mfma (check in Makefile), if so, maybe your machine doesn't support fma instruction. Please remove it and add -mtune=native

**Comment by HamzaShabbir517** [comment]
thanks @avishaitvila it work for me
