### ISSUE TITLE
Regarding csrrw instruction fail in case of write/swap to FRM

### ISSUE THREAD

**Issue by UrvishkumarPatel** [chipsalliance/SweRV-ISS#5]
In function 
    CsRegs<URV>::updateFcsrGroupForWrite(CsrNumber number, URV value)

for 
    (number == CsrNumber::FRM)

    setSimulatorRoundingMode(RoundingMode(value));

must be replaced by the following:

    setSimulatorRoundingMode(RoundingMode((fcsrVal >> shift)));

**Comment by jrahmeh** [comment]
Hi Urvish,

Many thanks for reporting this issue and providing a fix.  I added your fix
to the repository.

Joe
